export const PRODUCT_NAMES: Record<string, Record<string, string>> = {
  'GC-RIC-001': { en: "Premium White Rice 5kg", es: "Arroz Blanco Premium 5kg", fr: "Riz Blanc Premium 5kg" },
  'GC-RIC-002': { en: "Premium White Rice 10kg", es: "Arroz Blanco Premium 10kg", fr: "Riz Blanc Premium 10kg" },
  'GC-PAS-001': { en: "Spaghetti Pasta 500g", es: "Pasta Espagueti 500g", fr: "Pates Spaghetti 500g" },
  'GC-PAS-002': { en: "Elbow Macaroni Pasta 500g", es: "Pasta Macarrones 500g", fr: "Pates Coudes 500g" },
  'GC-FLR-001': { en: "All-Purpose Wheat Flour 2kg", es: "Harina de Trigo Multiuso 2kg", fr: "Farine de Ble Polyvalente 2kg" },
  'GC-FLR-002': { en: "All-Purpose Wheat Flour 5kg", es: "Harina de Trigo Multiuso 5kg", fr: "Farine de Ble Polyvalente 5kg" },
  'GC-CRM-001': { en: "Cornmeal 1kg", es: "Harina de Maiz 1kg", fr: "Farine de Mais 1kg" },
  'GC-CRM-002': { en: "Cornmeal 2.5kg", es: "Harina de Maiz 2.5kg", fr: "Farine de Mais 2.5kg" },
  'GC-CSF-001': { en: "Cassava Flour 1kg", es: "Harina de Yuca 1kg", fr: "Farine de Manioc 1kg" },
  'GC-BRF-001': { en: "Bread Flour 2kg", es: "Harina de Pan 2kg", fr: "Farine a Pain 2kg" },
  'GC-AVN-001': { en: "Rolled Oats 500g", es: "Avena en Hojuelas 500g", fr: "Flocons d'Avoine 500g" },
  'GC-PLN-001': { en: "Plantain Flour 500g", es: "Harina de Platano 500g", fr: "Farine de Banane Plantain 500g" },
  'GC-SEM-001': { en: "Wheat Semolina 1kg", es: "Semolina de Trigo 1kg", fr: "Semoulette de Ble 1kg" },
  'BL-BLK-001': { en: "Dried Black Beans 1kg", es: "Frijoles Negros Secos 1kg", fr: "Haricots Noirs Secs 1kg" },
  'BL-BLK-002': { en: "Dried Black Beans 2.5kg", es: "Frijoles Negros Secos 2.5kg", fr: "Haricots Noirs Secs 2.5kg" },
  'BL-RED-001': { en: "Dried Red Kidney Beans 1kg", es: "Frijoles Colorados Secos 1kg", fr: "Haricots Rouges Secs 1kg" },
  'BL-LNT-001': { en: "Dried Lentils 500g", es: "Lentejas Secas 500g", fr: "Lentilles Seches 500g" },
  'BL-CHK-001': { en: "Dried Chickpeas 500g", es: "Garbanzos Secos 500g", fr: "Pois Chiches Secs 500g" },
  'BL-SPL-001': { en: "Dried Split Peas 500g", es: "Chicharos Partidos 500g", fr: "Pois Casses Secs 500g" },
  'CN-TUN-001': { en: "Canned Tuna in Oil 150g (3-Pack)", es: "Atun en Aceite 150g (3-Pack)", fr: "Thon en Conserve a l'Huile 150g (3-Pack)" },
  'CN-TUN-002': { en: "Canned Tuna in Water 150g (6-Pack)", es: "Atun en Agua 150g (6-Pack)", fr: "Thon en Conserve a l'Eau 150g (6-Pack)" },
  'CN-SAR-001': { en: "Canned Sardines in Oil 125g (4-Pack)", es: "Sardinas en Aceite 125g (4-Pack)", fr: "Sardines en Conserve a l'Huile 125g (4-Pack)" },
  'CN-CHK-001': { en: "Canned Chicken Breast 350g", es: "Pollo en Conserva 350g", fr: "Poitrine de Poulet en Conserve 350g" },
  'CN-VEG-001': { en: "Canned Mixed Vegetables 400g", es: "Vegetales Mixtos en Conserva 400g", fr: "Legumes Mixtes en Conserve 400g" },
  'CN-SPM-001': { en: "Luncheon Meat 340g", es: "Carne de Almuerzo Tipo Spam 340g", fr: "Viande d'Dejeuner 340g" },
  'CN-SPM-002': { en: "Luncheon Meat 340g (3-Pack)", es: "Carne de Almuerzo Tipo Spam 340g (3-Pack)", fr: "Viande d'Dejeuner 340g (3-Pack)" },
  'FP-AVO-001': { en: "Fresh Cuban Avocados (3 units)", es: "Aguacate Cubano Fresco (3 unidades)", fr: "Avocats Cubains Frais (3 unites)" },
  'FP-AVO-002': { en: "Fresh Cuban Avocados (6 units)", es: "Aguacate Cubano Fresco (6 unidades)", fr: "Avocats Cubains Frais (6 unites)" },
  'FP-AVO-003': { en: "Mamey Avocados (3 units)", es: "Aguacate Mamey (3 unidades)", fr: "Avocats Mamey (3 unites)" },
  'FP-PLT-001': { en: "Ripe Plantains (6 units)", es: "Platanos Maduros (6 unidades)", fr: "Bananes Plantains Mures (6 unites)" },
  'FP-PLT-002': { en: "Green Plantains (6 units)", es: "Platanos Verdes (6 unidades)", fr: "Bananes Plantains Vertes (6 unites)" },
  'FP-BON-001': { en: "Cuban Sweet Potato 2kg", es: "Boniato (Sweet Potato) 2kg", fr: "Patate Douce Cubaine 2kg" },
  'FP-YUC-001': { en: "Fresh Cassava 2kg", es: "Yuca Fresca 2kg", fr: "Manioc Frais 2kg" },
  'FP-MNG-001': { en: "Fresh Mangoes (4 units)", es: "Mangos Frescos (4 unidades)", fr: "Mangues Fraiches (4 unites)" },
  'FP-PAP-001': { en: "Fresh Papaya (1 large unit)", es: "Papaya Fresca (1 unidad grande)", fr: "Papaye Fraiche (1 grosse unite)" },
  'FP-GUA-001': { en: "Fresh Guavas (6 units)", es: "Guayabas Frescas (6 unidades)", fr: "Goyaves Fraiches (6 unites)" },
  'FP-COC-001': { en: "Fresh Coconuts (2 units)", es: "Coco Fresco (2 unidades)", fr: "Noix de Coco Fraiches (2 unites)" },
  'FP-GBN-001': { en: "Fresh Soursop (1 unit)", es: "Guanabana Fresca (1 unidad)", fr: "Corossol Frais (1 unite)" },
  'FP-CIR-001': { en: "Tropical Plums (500g)", es: "Ciruelas Tropicales (500g)", fr: "Prunes Tropicales (500g)" },
  'CB-CUB-001': { en: "Cubita Dark Roast Ground Coffee 250g", es: "Cafe Cubita Molido Oscuro 250g", fr: "Cafe Cubita Moulu Torrefaction Noire 250g" },
  'CB-CUB-002': { en: "Cubita Dark Roast Ground Coffee 500g", es: "Cafe Cubita Molido Oscuro 500g", fr: "Cafe Cubita Moulu Torrefaction Noire 500g" },
  'CB-CUB-003': { en: "Cubita Medium Roast Ground Coffee 250g", es: "Cafe Cubita Molido Medio 250g", fr: "Cafe Cubita Moulu Torrefaction Moyenne 250g" },
  'CB-SER-001': { en: "Serrano Dark Roast Ground Coffee 250g", es: "Cafe Serrano Molido Oscuro 250g", fr: "Cafe Serrano Moulu Torrefaction Noire 250g" },
  'CB-SER-002': { en: "Serrano Whole Bean Coffee 500g", es: "Cafe Serrano Grano Entero 500g", fr: "Cafe Serrano en Grains Entiers 500g" },
  'CB-SER-003': { en: "Serrano Light Roast Ground Coffee 250g", es: "Cafe Serrano Molido Suave 250g", fr: "Cafe Serrano Moulu Torrefaction Claire 250g" },
  'CB-TUR-001': { en: "Turquino Mountain Coffee 250g", es: "Cafe Turquino Montanes 250g", fr: "Cafe Turquino des Montagnes 250g" },
  'CB-BLD-001': { en: "Cuban Espresso Blend Coffee 250g", es: "Cafe Mezcla Cubana (Espresso Blend) 250g", fr: "Cafe Melange Cubain (Espresso Blend) 250g" },
  'CB-BLD-002': { en: "Decaffeinated Ground Coffee 250g", es: "Cafe Descafeinado Molido 250g", fr: "Cafe Moulu Decafeine 250g" },
  'CB-INS-001': { en: "Instant Coffee 200g", es: "Cafe Instantaneo 200g", fr: "Cafe Instantane 200g" },
  'DM-PWM-001': { en: "Whole Powdered Milk 800g", es: "Leche en Polvo Entera 800g", fr: "Lait Entier en Poudre 800g" },
  'DM-PWM-002': { en: "Whole Powdered Milk 2.5kg", es: "Leche en Polvo Entera 2.5kg", fr: "Lait Entier en Poudre 2.5kg" },
  'DM-SKM-001': { en: "Skim Powdered Milk 800g", es: "Leche en Polvo Descremada 800g", fr: "Lait Ecreme en Poudre 800g" },
  'DM-CON-001': { en: "Sweetened Condensed Milk 395g", es: "Leche Condensada 395g", fr: "Lait Condense Sucre 395g" },
  'DM-CON-002': { en: "Sweetened Condensed Milk 395g (3-Pack)", es: "Leche Condensada 395g (3-Pack)", fr: "Lait Condense Sucre 395g (3-Pack)" },
  'DM-EVP-001': { en: "Evaporated Milk 370g", es: "Leche Evaporada 370g", fr: "Lait Evapore 370g" },
  'DM-CRM-001': { en: "UHT Heavy Cream 200ml (3-Pack)", es: "Crema de Leche UHT 200ml (3-Pack)", fr: "Creme Liquide UHT 200ml (3-Pack)" },
  'JP-MNG-001': { en: "Mango Juice 1L (3-Pack)", es: "Jugo de Mango 1L (3-Pack)", fr: "Jus de Mangue 1L (3-Pack)" },
  'JP-PAP-001': { en: "Papaya Juice 1L (3-Pack)", es: "Jugo de Papaya 1L (3-Pack)", fr: "Jus de Papaye 1L (3-Pack)" },
  'JP-GUA-001': { en: "Guava Juice 1L (3-Pack)", es: "Jugo de Guayaba 1L (3-Pack)", fr: "Jus de Goyave 1L (3-Pack)" },
  'JP-COC-001': { en: "Coconut Water 330ml (6-Pack)", es: "Agua de Coco 330ml (6-Pack)", fr: "Eau de Coco 330ml (6-Pack)" },
  'JP-COC-002': { en: "Coconut Milk 400ml (3-Pack)", es: "Leche de Coco 400ml (3-Pack)", fr: "Lait de Coco 400ml (3-Pack)" },
  'JP-GBN-001': { en: "Soursop Juice 1L (3-Pack)", es: "Jugo de Guanabana 1L (3-Pack)", fr: "Jus de Corossol 1L (3-Pack)" },
  'JP-MIX-001': { en: "Tropical Mixed Juice Pack (6 units)", es: "Pack Tropical Surtido (6 unidades)", fr: "Pack Tropical Assortis (6 unites)" },
  'JP-CIR-001': { en: "Tropical Plum Juice 1L (3-Pack)", es: "Jugo de Ciruela 1L (3-Pack)", fr: "Jus de Prune Tropicale 1L (3-Pack)" },
  'JP-PSN-001': { en: "Passion Fruit Juice 1L (3-Pack)", es: "Jugo de Maracuya 1L (3-Pack)", fr: "Jus de Fruit de la Passion 1L (3-Pack)" },
  'AE-RCK-001': { en: "Low-Energy Electric Rice Cooker 1.8L", es: "Olla Arrocera Electrica 1.8L (Bajo Consumo)", fr: "Cuiseur a Riz Electrique Econome 1.8L" },
  'AE-FAN-001': { en: "Solar DC Fan 16 inch", es: "Ventilador Solar DC 16\"", fr: "Ventilateur Solaire DC 16 pouces" },
  'AE-FAN-002': { en: "Solar DC Ceiling Fan 52 inch", es: "Ventilador de Techo Solar DC 52\"", fr: "Ventilateur de Plafond Solaire DC 52 pouces" },
  'AE-REF-001': { en: "DC Mini Refrigerator 50L", es: "Mini Refrigerador 12V/DC 50L", fr: "Mini Refrigerateur DC 50L" },
  'AE-REF-002': { en: "Solar DC Refrigerator 100L", es: "Refrigerador Solar DC 100L", fr: "Refrigerateur Solaire DC 100L" },
  'AE-LED-001': { en: "Solar LED Lighting Kit (6 bulbs)", es: "Kit Iluminacion LED Solar (6 bombillas)", fr: "Kit d'Eclairage LED Solaire (6 ampoules)" },
  'AE-CHG-001': { en: "Multi-Port Solar USB Charger", es: "Cargador Solar USB Multi-Puerto", fr: "Chargeur USB Solaire Multi-Port" },
  'SE-PNL-001': { en: "Portable Solar Panel 100W", es: "Panel Solar Portatil 100W", fr: "Panneau Solaire Portable 100W" },
  'SE-PNL-002': { en: "Portable Solar Panel 200W", es: "Panel Solar Portatil 200W", fr: "Panneau Solaire Portable 200W" },
  'SE-PNL-003': { en: "Portable Solar Panel 400W", es: "Panel Solar Portatil 400W", fr: "Panneau Solaire Portable 400W" },
  'SE-RPM-001': { en: "Rooftop Solar Panel Module 300W", es: "Modulo Solar para Techo 300W", fr: "Module Panneau Solaire de Toit 300W" },
  'SE-RPM-002': { en: "Rooftop Solar Panel Module 550W", es: "Modulo Solar para Techo 550W", fr: "Module Panneau Solaire de Toit 550W" },
  'SE-BAT-001': { en: "Solar Battery Storage System 5kWh", es: "Sistema de Bateria Solar 5kWh", fr: "Systeme de Stockage Batterie Solaire 5kWh" },
  'SE-BAT-002': { en: "Solar Battery Storage System 10kWh", es: "Sistema de Bateria Solar 10kWh", fr: "Systeme de Stockage Batterie Solaire 10kWh" },
  'SE-INV-001': { en: "Solar Inverter 3kW", es: "Inversor Solar 3kW", fr: "Onduleur Solaire 3kW" },
  'SE-INV-002': { en: "Solar Inverter 5kW", es: "Inversor Solar 5kW", fr: "Onduleur Solaire 5kW" },
  'SE-PWB-001': { en: "Solar Power Bank 20,000mAh", es: "Power Bank Solar 20,000mAh", fr: "Batterie Externe Solaire 20 000mAh" },
  'SE-PWB-002': { en: "Solar Power Bank 50,000mAh", es: "Power Bank Solar 50,000mAh", fr: "Batterie Externe Solaire 50 000mAh" },
  'SE-FLD-001': { en: "Foldable Solar Kit 60W", es: "Kit Solar Plegable 60W", fr: "Kit Solaire Pliable 60W" },
  'SE-FLD-002': { en: "Foldable Solar Kit 120W", es: "Kit Solar Plegable 120W", fr: "Kit Solaire Pliable 120W" },
  'SE-BDL-001': { en: "Basic Home Solar Kit", es: "Kit Solar Basico para Hogar", fr: "Kit Solaire Basique pour Maison" },
  'SE-BDL-002': { en: "Solar Lighting Kit", es: "Kit de Iluminacion Solar", fr: "Kit d'Eclairage Solaire" },
  'DF-DSL-001': { en: "Diesel 5L Container", es: "Diesel 5L Contenedor", fr: "Diesel Conteneur 5L" },
  'DF-DSL-002': { en: "Diesel 20L Container", es: "Diesel 20L Contenedor", fr: "Diesel Conteneur 20L" },
  'DF-DSL-003': { en: "Diesel 50L Drum", es: "Diesel 50L Barril", fr: "Diesel Baril 50L" },
  'DF-STR-001': { en: "Fuel Storage Barrel 200L", es: "Barril de Almacenamiento 200L", fr: "Baril de Stockage de Carburant 200L" },
  'DF-GEN-001': { en: "Diesel Generator 3.5kW", es: "Generador Diesel 3.5kW", fr: "Generateur Diesel 3.5kW" },
  'DF-GEN-002': { en: "Diesel Generator 7kW", es: "Generador Diesel 7kW", fr: "Generateur Diesel 7kW" },
  'DF-GEN-003': { en: "Portable Gasoline Generator 2kW", es: "Generador Portatil Gasolina 2kW", fr: "Generateur Portable Essence 2kW" },
  'DF-PMP-001': { en: "Manual Fuel Transfer Pump", es: "Bomba de Combustible Manual", fr: "Pompe de Transfert de Carburant Manuel" },
  'DF-BDL-001': { en: "Generator + Initial Fuel Starter Bundle", es: "Kit Generador + Combustible Inicial", fr: "Kit Generateur + Carburant Initial" },
  'DF-BDL-002': { en: "Farm Power Energy Bundle", es: "Kit Energia para Finca", fr: "Kit d'Energie pour Ferme" },
  'BS-LIT-001': { en: "Lithium Battery 100Ah 12V", es: "Bateria de Litio 100Ah 12V", fr: "Batterie au Lithium 100Ah 12V" },
  'BS-LIT-002': { en: "Lithium Battery 200Ah 12V", es: "Bateria de Litio 200Ah 12V", fr: "Batterie au Lithium 200Ah 12V" },
  'BS-LED-001': { en: "Deep-Cycle Lead-Acid Battery 100Ah 12V", es: "Bateria Ciclo Profundo (Plomo) 100Ah 12V", fr: "Batterie Plomb Cycle Profond 100Ah 12V" },
  'BS-LED-002': { en: "Deep-Cycle Lead-Acid Battery 200Ah 12V", es: "Bateria Ciclo Profundo (Plomo) 200Ah 12V", fr: "Batterie Plomb Cycle Profond 200Ah 12V" },
  'BS-PPS-001': { en: "Portable Power Station 500Wh", es: "Estacion de Energia Portatil 500Wh", fr: "Station d'Energie Portable 500Wh" },
  'BS-PPS-002': { en: "Portable Power Station 1500Wh", es: "Estacion de Energia Portatil 1500Wh", fr: "Station d'Energie Portable 1500Wh" },
  'BS-SBK-001': { en: "Solar Battery Bank 2.4kWh", es: "Banco de Baterias Solar 2.4kWh", fr: "Banc de Batteries Solaire 2.4kWh" },
  'MG-OGK-001': { en: "Complete Off-Grid Solar Kit 3kW", es: "Kit Solar Off-Grid Completo 3kW", fr: "Kit Solaire Complet Off-Grid 3kW" },
  'MG-OGK-002': { en: "Complete Off-Grid Solar Kit 5kW", es: "Kit Solar Off-Grid Completo 5kW", fr: "Kit Solaire Complet Off-Grid 5kW" },
  'MG-HYB-001': { en: "Hybrid Solar + Generator System", es: "Sistema Hibrido Solar + Generador", fr: "Systeme Hybride Solaire + Generateur" },
  'MG-HYB-002': { en: "Premium Hybrid Solar + Generator System", es: "Sistema Hibrido Solar + Generador Premium", fr: "Systeme Hybride Solaire + Generateur Premium" },
  'MG-CTR-001': { en: "Smart Energy Controller", es: "Controlador Inteligente de Energia", fr: "Controleur d'Energie Intelligent" },
  'MG-PDB-001': { en: "Electrical Power Distribution Box", es: "Caja de Distribucion Electrica", fr: "Boite de Distribution Electrique" },
  // Essential Bundles
  'BX-FAM-001': { en: "Essential Family Bundle", es: "Paquete Familiar Esencial", fr: "Pack Familial Essentiel" },
  'BX-PRO-001': { en: "Protein Power Bundle", es: "Paquete de Proteinas", fr: "Pack Proteines" },
  'BX-BEB-001': { en: "Tropical Drinks Bundle", es: "Paquete de Bebidas Tropicales", fr: "Pack Boissons Tropicales" },
  'BX-CAF-001': { en: "Cuban Coffee Lovers Bundle", es: "Paquete Cafetalero Cubano", fr: "Pack Cafe Cubain" },
  'BX-FRU-001': { en: "Fresh Tropical Fruits Bundle", es: "Paquete de Frutas Frescas", fr: "Pack Fruits Tropicaux Frais" },
  'BX-SOL-001': { en: "Basic Solar Starter Bundle", es: "Paquete Solar Basico", fr: "Pack Solaire de Base" },
  'BX-DES-001': { en: "Complete Pantry Bundle", es: "Paquete Despensa Completa", fr: "Pack Garde-Manger Complet" },
  'BX-BLK-001': { en: "All-In-One Mega Bundle", es: "Mega Paquete Todo Incluido", fr: "Mega Pack Tout Compris" },
};

/**
 * Translate a product name by SKU. Falls back to the original name if SKU not found.
 */
export function tProductName(lang: string, sku: string | null | undefined, fallback: string): string {
  if (!sku) return fallback;
  const entry = PRODUCT_NAMES[sku];
  if (!entry) return fallback;
  return entry[lang] || entry['en'] || fallback;
}
